import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import ReactQueryProvider from "@/app/providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="light"  lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
      <ReactQueryProvider>
          {children}
      </ReactQueryProvider>
      </body>
    </html>
  );
}


import FooterLayout from "@/app/components/layout/Footer";

/*
export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html>
        <body>
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
{/!*
        <FooterLayout/>
*!/}
        </body>
        </html>
    )
}*/
