import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import React from "react";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

//Navbar
import Top_bar from "@/components/layout/top_bar"

import Navbar from "@/components/layout/Navigationbar/Navbar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className="light"  lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
        <Top_bar/>
        <Navbar/>
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
        <script src="../path/to/flowbite/dist/flowbite.min.js" async/>
        </body>
        </html>
    );
}


import FooterLayout from "@/components/layout/Footer";

/*
export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html>
        <body>
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
{/!*
        <FooterLayout/>
*!/}
        </body>
        </html>
    )
}*/
